### ISSUE TITLE
Move netafilter.in to HTTPS

### ISSUE THREAD

**Issue by shreyas-satish** [folography/visavis#16]

**Comment by shreyas-satish** [comment]
One option is to move to [Heroku](https://devcenter.heroku.com/articles/ssl-endpoint), since [Github](https://github.com/isaacs/github/issues/156) doesn't support HTTPS for custom domains ATM.

**Comment by planemad** [comment]
Done

**Comment by shreyas-satish** [comment]
We still don't have a valid SSL certificate for `netafilter.in`. This should probably be re-opened.
